### ISSUE TITLE
Should this still work in 2019?

### ISSUE THREAD

**Issue by CCLDArjun** [sjl/flask-csrf#4]

**Comment by sjl** [comment]
I haven't touched flask (or this project) in about nine years.  If Flask has made backwards-incompatible changes that broke this 51-line project in that time, then it probably won't work.

If someone else [wants to maintain it](http://stevelosh.com/projects/#looking-for-maintainers) I'm happy to add a link to a maintained fork to this repo's README, but I'm not maintaining it myself any more.
